version: '3'
services:

  eureka-server:
    build:
      context: ./EurekaServer
    ports:
      - "8761:8761"
    networks:
      - my_network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - my_network

  service1:
    build:
      context: ./UserAccess
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - my_network



networks:
  my_network:
    external: true
