version: '3.8'

services:
  eureka-server:
    image: bessem1/eureka-server:1.0
    container_name: my-eureka-server
    ports:
      - "8761:8761"
    environment:
      - server.port=8761
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
      - eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

  mysql-backend:
    image: mysql:latest
    container_name: mysql-backend
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=backend
    ports:
      - "3306:3306"
    volumes:
      - mysql-backend-data:/var/lib/mysql

  mysql-megagolive:
    image: mysql:latest
    container_name: mysql-megagolive
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=megagolive001
    ports:
      - "3307:3306"
    volumes:
      - mysql-megagolive-data:/var/lib/mysql

  user-access:
    image: bessem1/user-access:1.0
    container_name: my-user-access
    ports:
      - "9002:9002"
    environment:
      - server.port=9002
      - spring.datasource.url=jdbc:mysql://mysql-backend:3306/backend?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

  api-gateway:
    image: bessem1/api-gateway:1.0
    container_name: my-api-gateway
    ports:
      - "8088:8088"
    environment:
      - server.port=8088
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
      - spring.cloud.gateway.routes[0].id=service1
      - spring.cloud.gateway.routes[0].uri=http://user-access:9002
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
      - spring.cloud.gateway.routes[0].predicates[1]=Path=/Utilisateur/**
      - spring.cloud.gateway.routes[1].id=service2
      - spring.cloud.gateway.routes[1].uri=http://comparer-service:9001
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/Comparator/**
      - spring.cloud.gateway.routes[1].predicates[1]=Path=/FileCntrl/**
      - spring.cloud.gateway.routes[2].id=ScriptTransformer
      - spring.cloud.gateway.routes[2].uri=http://script-transformer:9003
      - spring.cloud.gateway.routes[2].predicates[0]=Path=/ScriptTransformer/result
      - spring.cloud.gateway.routes[2].predicates[1]=Path=/Simulation/**

  script-transformer:
    image: bessem1/scriptediting:1.0
    container_name: script-transformer
    ports:
      - "9003:9003"
    environment:
      - server.port=9003
      - spring.datasource.url=jdbc:mysql://mysql-megagolive:3306/megagolive001?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

  comparer-service:
    image: bessem1/comparer-ear:1.0
    container_name: comparer-service
    ports:
      - "9001:9001"
    environment:
      - server.port=9001
      - spring.datasource.url=jdbc:mysql://mysql-megagolive:3306/megagolive001?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

volumes:
  mysql-backend-data:
  mysql-megagolive-data:
