

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

    serviceUrl:
      defaultZone: https://${eureka-MegaRunLive-service}:${server.port}/eureka/

  server:
    enableSelfPreservation: false # Disable in development for quicker registry updates
